apiVersion: apps/v1
kind: Deployment
metadata:
  name: devspaces-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devspaces-demo
  template:
    metadata:
      labels:
        app: devspaces-demo
    spec:
      containers:
        - name: flask-app
          image: python:3.9-slim
          command: ["sleep", "infinity"]
          ports:
            - containerPort: 8080
